2025-06-05 20:03:07.941944-03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "TELEFONE CHARACTER VARYING(13)": "'(62)99902-8535' (14)"; SQL statement:
insert into cliente (email,nome,telefone,id) values (?,?,?,?) [22001-232]
2025-06-07 22:27:46.165738-03:00 jdbc[92]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "FUNCIONARIO" not found; SQL statement:
DROP TABLE FUNCIONARIO [42102-232]
2025-06-08 02:20:13.419613-03:00 jdbc[64]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "TELEFONE CHARACTER VARYING(20)": "'testekkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk... (86)"; SQL statement:
update cliente set email=?,nome=?,telefone=? where id=? [22001-232]
2025-06-08 02:52:31.935266-03:00 jdbc[15]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:368)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:483)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:747)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
